serenity.project.name = Confecamaras

# ==============================
# CAPTURAS DE PANTALLA
# ==============================
# Apto para Screenplay. Captura cada acción (Click, Enter, WaitUntil, etc)
serenity.take.screenshots = FOR_EACH_ACTION

# ==============================
# DRIVER PERSONALIZADO HEALENIUM
# ==============================
webdriver.driver = provided
webdriver.provided.type = myhealenium
webdriver.provided.myhealenium = com.co.confecamaras.navigation.HealeniumDriverProvider

# ==============================
# CONFIG CHROME
# ==============================
serenity.browser.maximized = true
webdriver.wait.for.timeout = 20000
driver.page_load_strategy = normal

chrome.switches = """--start-maximized;
--test-type;
--no-sandbox;
--ignore-certificate-errors;
--disable-default-apps;
--disable-extensions-file-access-check;
--incognito;
--disable-infobars;
--disable-gpu"""

# ==============================
# CONFIGURACIÓN DE AMBIENTES
# ==============================
environments {
default {
webdriver.base.url = "https://siifrontqa.confecamaras.co/"
}


