name: CI - Ejecutar Feature por Nombre

on:
  workflow_dispatch:
    inputs:
      feature_name:
        description: 'Nombre del feature (ej: login.feature)'
        required: true
        default: 'login.feature'

jobs:
  ejecutar-feature:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: projectconfecamaras-master

    steps:
    - name: Paso 1 - Descargar el código
      uses: actions/checkout@v4

    - name: Paso 2 - Instalar Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Paso 3 - Dar permisos a Gradle
      run: chmod +x gradlew

    - name: Paso 4 - Ejecutar feature seleccionado
      run: |
        FEATURE_PATH="src/test/resources/features/${{ github.event.inputs.feature_name }}"
        echo "Ejecutando feature: $FEATURE_PATH"
        ./gradlew clean test -Dcucumber.features="$FEATURE_PATH"
