name: Proyecto Confecamaras - Serenity CI

on:
  workflow_dispatch:
    inputs:
      feature_folder:
        description: "Carpeta del feature (ej: registros_publicos)"
        required: true
      feature_file:
        description: "Archivo feature (ej: simulacion.feature)"
        required: true

jobs:
  serenity-tests:
    runs-on: ubuntu-latest

    env:
      CI: true
      HEALENIUM_PROVIDER: ""   # <- Apaga Healenium

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Validar feature seleccionado
        run: |
          FEATURE_PATH="src/test/resources/features/${{ github.event.inputs.feature_folder }}/${{ github.event.inputs.feature_file }}"
          echo "Feature seleccionado: $FEATURE_PATH"

          if [ ! -f "$FEATURE_PATH" ]; then
            echo "❌ Feature no encontrado"
            exit 1
          fi

          echo "FEATURE_PATH=$FEATURE_PATH" >> $GITHUB_ENV

      - name: Ejecutar Serenity
        run: |
          ./gradlew clean test aggregate \
            -Dcucumber.features=$FEATURE_PATH \
            -Denvironment=ci \
            -Dci=true

      - name: Subir reporte Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity

      - name: Instrucciones QA
        if: always()
        run: |
          echo "## 📊 Reporte Serenity" >> $GITHUB_STEP_SUMMARY
          echo "1. Abrir ejecución" >> $GITHUB_STEP_SUMMARY
          echo "2. Descargar artifact serenity-report" >> $GITHUB_STEP_SUMMARY
          echo "3. Abrir index.html" >> $GITHUB_STEP_SUMMARY
