name: CI - Ejecutar Feature con Reporte Serenity

on:
  workflow_dispatch:
    inputs:
      feature_name:
        description: 'indicar el nombre del archivo .feature a ejecutar'
        required: true
        default: ''

jobs:
  ejecutar-feature:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: projectconfecamaras-master

    steps:
    - name: Paso 1 - Descargar el código
      uses: actions/checkout@v4

    - name: Paso 2 - Instalar Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Paso 3 - Dar permisos a Gradle
      run: chmod +x gradlew

    - name: Paso 4 - Ejecutar feature seleccionado
      run: |
        FEATURE_PATH="src/test/resources/features/registros_publicos/${{ github.event.inputs.feature_name }}"

        if [ ! -f "$FEATURE_PATH" ]; then
          echo "❌ Feature no encontrado: $FEATURE_PATH"
          exit 1
        fi

        ./gradlew clean test aggregate -Dcucumber.features="$FEATURE_PATH"

    - name: Paso 5 - Publicar reporte Serenity
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: serenity-report
        path: projectconfecamaras-master/target/site/serenity
